ALTER TABLE sections      ADD COLUMN IF NOT EXISTS image_url VARCHAR(500);
ALTER TABLE categories    ADD COLUMN IF NOT EXISTS image_url VARCHAR(500);
ALTER TABLE product_groups ADD COLUMN IF NOT EXISTS image_url VARCHAR(500);
